### ISSUE TITLE
modèles FMI 32 bits

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#100]
In GitLab by @schueller on Apr 30, 2018, 10:58

À partir de la version 4.0, on a fourni des binaires 64bits qui ne peuvent donc pas ouvrir des modèles 32 bits.

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 30, 2018, 10:59

```
Traceback (most recent call last):
  File "C:\Users\c61372\AppData\Local\Continuum\otconda2\lib\site-packages\otfmi\fmi.py", line 33, in load_fmu
    return pyfmi.load_fmu(path_fmu, kind="auto")
  File "src\pyfmi\fmi.pyx", line 7201, in pyfmi.fmi.load_fmu (src\pyfmi\fmi.c:78974)
  File "src\pyfmi\fmi.pyx", line 5662, in pyfmi.fmi.FMUModelCS2.__init__ (src\pyfmi\fmi.c:63082)
  File "src\pyfmi\fmi.pyx", line 3420, in pyfmi.fmi.FMUModelBase2.__init__ (src\pyfmi\fmi.c:37621)
pyfmi.fmi.FMUException: Error loading the binary. The FMU contains no binary for
 this platform.
```

**Comment by adumasphi** [comment]
In GitLab by @schueller on May 11, 2018, 16:50

Le sort des binaires conda 32 bits semble fixé: https://github.com/conda-forge/staged-recipes/issues/5640

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Jul 10, 2018, 15:48

Ok : la question est donc tranchée.

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Jul 10, 2018, 15:48

closed
