### ISSUE TITLE
Les exceptions Python ne sont pas capturées

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#262]
In GitLab by @mbaudin47 on Feb 18, 2020, 13:57

Dans un modèle de couplage, j’ai placé les paramètres suivants, puis j’ai évalué le modèle.

![Screenshot_from_2020-02-18_12-11-49](https://my-gitlab-bucket.s3.amazonaws.com/294647435/d9ecc30b29cfe0ed235a758f280186a1.png)

Une exception est affichée dans la console Python :

```
$ python: can't open file 'external_program.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 46, in _exec
  File "/tmp/.mount_persalX2xlM3/usr/lib/python3.7/site-packages/openturns/coupling_tools.py", line 248, in execute
    'Command "' + cmd + '" returned exit code ' + str(ret))
RuntimeError: Command "python external_program.py  input.txt" returned exit code 2
```

Mais cette exception n’est pas capturée dans Persalys. Cela rend impossible le debug si on lance Persalys graphiquement. Pour contourner le bug, on doit ouvrir Persalys depuis une console Linux.

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 20, 2020, 11:43

https://github.com/openturns/openturns/pull/1370 (openturns 1.15)

also needs f44788d0cd30c8b9e95a3a5872748f92cb3f4af7

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 20, 2020, 13:36

closed
