### ISSUE TITLE
Avec une AppImage, le fichier d’entrée est généré dans le répertoire temporaire

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#264]
In GitLab by @mbaudin47 on Feb 18, 2020, 14:01

Lorsque j’évalue le modèle physique, le fichier d’entrée est généré dans le répertoire temporaire :

```
$ ls /tmp/persalys_8030f8e663d6b0c634b0e6a1d89c0c50a76b2b20/
input.txt
```

C’est pourquoi le programme n’est pas exécuté correctement. Une erreur est affichée dans la console :

```
$ Traceback (most recent call last):
  File "<string>", line 41, in _exec
  File "/tmp/.mount_persalvCedxo/usr/lib/python3.7/site-packages/openturns/coupling_tools.py", line 119, in replace
    infile_handle = open(infile, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'input_template.txt'
```

Mais cette erreur n’est pas remontée dans PERSALYS.

J’ai tenté de précéder l’exécution du code Python par la commande Shell :

```
cd /home/osboxes/Documents/AG2020-Appli/jouet/jouet-basique
```

mais cela ne change rien. En effet, lorsque la seconde commande est configurée à “echo $PWD”, le chemin suivant s’affiche dans la console :

```
$ /tmp/persalys_cac5dc31f20128acdb988c8f9be1f9ea0bb6fb9e
```

En conséquence, on ne peux pas utiliser le modèle de couplage depuis une version de Persalys dont le binaire est une AppImage.

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 19, 2020, 10:16

C'est voulu, afin d'isoler chaque evaluation dans son propre répertoire.

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 19, 2020, 10:16

closed

**Comment by adumasphi** [comment]
In GitLab by @mbaudin47 on Feb 20, 2020, 11:00

Ok, je comprends. Mais cela rends la fonctionnalité inutilisable.

**Comment by adumasphi** [comment]
In GitLab by @mbaudin47 on Feb 20, 2020, 11:00

reopened

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 20, 2020, 11:10

Le fichier d'entrée est généré dans un dossier temporaire pour chaque point, et la commande est lancée à partir de ce dossier temporaire, normalement il y a tout ce qu'il faut.

Tu veux bien détailler ton use-case ?

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Feb 20, 2020, 11:10

closed

**Comment by adumasphi** [comment]
In GitLab by @mbaudin47 on Feb 24, 2020, 17:43

Je te passe le cas-test. C'est le cas jouet du CDC. 

* Programme : "python /chemin/vers/external_program.py input.txt"
* Fichier d'entrée modèle : input_template.txt
* Fichier de sortie : output.txt

[UseCase-Jouet.zip](/uploads/07ab0e933fd3c35f3c1a1a88db843eb9/UseCase-Jouet.zip)

**Comment by adumasphi** [comment]
In GitLab by @mbaudin47 on Feb 24, 2020, 17:59

Je n'avais pas compris que le fichier "input.txt" était généré dans un répertoire temporaire, mais c'est évident (c'est même moi qui l'ai demandé !)

Voici la configuration qui fonctionne :

![Capture-2](https://my-gitlab-bucket.s3.amazonaws.com/294647435/af1302470b7c12070d0ff1ec57c2cad4.PNG)

![Capture-3](https://my-gitlab-bucket.s3.amazonaws.com/294647435/1b0452afaf4c1ca4b38bf0d5471454e0.PNG)

Puisque c'est OK, je ferme ce ticket.
