### ISSUE TITLE
AppImage: Freeze LD_LIBRARY_PATH, PYTHONPATH - [merged]

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#723]
In GitLab by @jschueller on Mar 23, 2021, 11:10

_Merges noext -> master_

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 11:10

cc @YomGarcia @gosset

**Comment by adumasphi** [comment]
In GitLab by @YomGarcia on Mar 23, 2021, 11:11

approved this merge request

**Comment by adumasphi** [comment]
In GitLab by @YomGarcia on Mar 23, 2021, 11:16

Quid du PYTHONPATH pour persalys-soteria? Je peux toujours le faire pointer vers les modules python qui m'interesse?

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 11:17

oui en modifiant au même endroit, c'est juste que par defaut ça n'accepte pas ce qui vient de dehors

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 11:56

tu avais:
`export PYTHONPATH=${HERE}/usr/lib/python3.8/site-packages:${PERFECT_PATH}`

on peut peut-être quand même autoriser les modèles externes;
est-ce que ça marche avec `export PYTHONPATH=${HERE}/usr/lib/python3.8/site-packages:${PERFECT_PATH}:${PYTHONPATH}` ?

et `export PYTHONPATH=${HERE}/usr/lib/python3.8/site-packages:${PYTHONPATH}` ?

**Comment by adumasphi** [comment]
In GitLab by @YomGarcia on Mar 23, 2021, 12:14

Les deux ne marchent pas 
```python
Traceback (most recent call last):
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/core/multiarray.py", line 7, in <module>
    __bootstrap__()
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/core/multiarray.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/tmp/.mount_persalNi8nd5/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpython3.6.so.1.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_persalNi8nd5/usr/lib/python3.8/site-packages/persalys/soteria/prfhelper.py", line 4, in <module>
    from PDM.BasicTypes import Integer, Coefficient
  File "/home/garcia/work/soteria2020/PDM/__init__.py", line 52, in <module>
    xmlserial.register_module("PDM." + module_name)
  File "/home/garcia/work/soteria2020/PerfectWorkFlowAPI/xmlserial.py", line 493, in register_module
    register_module_sub( modulename  )
  File "/home/garcia/work/soteria2020/PerfectWorkFlowAPI/xmlserial.py", line 482, in register_module_sub
    m = __import__( name, globals(), locals(), ['*'] )
  File "/home/garcia/work/soteria2020/PDM/BasicTypes.py", line 36, in <module>
    import numpy
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/garcia/work/salome_meca/V2019.0.3_universal/prerequisites/Numpy-1151/lib/python3.6/site-packages/numpy-1.15.1-py3.6-linux-x86_64.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libpython3.6.so.1.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
```

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 12:15

ok, bon ben je laisse comme ça

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 12:16

added 7 commits

<ul><li>6cee01dc...d65d14c5 - 6 commits from branch <code>master</code></li><li>1f572fe8 - AppImage: Freeze LD_LIBRARY_PATH, PYTHONPATH</li></ul>

[Compare with previous version](/ot-edf/otgui/-/merge_requests/421/diffs?diff_id=4253&start_sha=6cee01dc9fb039fe344ffb71221d03ffacde14a8)

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 12:17

enabled an automatic merge when the pipeline for 1f572fe8a55fa1a47e6e053ebf35705e1eef1458 succeeds

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 12:54

merged

**Comment by adumasphi** [comment]
In GitLab by @jschueller on Mar 23, 2021, 12:54

mentioned in commit 64c783be89e6467342dd2fbe0e2fadd15b674754
