### ISSUE TITLE
Modèles FMI dans otgui-4.0dev-py2.7-x86_64

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#96]
In GitLab by @mbaudin on Apr 3, 2018, 11:56

Un utilisateur (de la DTG) a essayé d'utiliser la dernière version de l'interface graphique avec un modèle FMI, mais cela n'a pas marché. J'arrive à reproduire le bug chez moi.
* Dans la gui, j'importe le modèle FMU suivant : [MozartExistantMovie_CasSimplifie04.fmu](/uploads/c757682af022724eeed75a50298ffad8/MozartExistantMovie_CasSimplifie04.fmu). L'interface graphique affiche l'erreur "ImportError". L'exception est la suivante: 

```
WRN - The configuration file has not been found, using default parameters.
Traceback (most recent call last):
  File "C:\Users\Baudin\otconda2\lib\site-packages\otfmi\__init__.py", line 3, in <module>
    from .otfmi import FMUFunction, OpenTURNSFMUFunction
  File "C:\Users\Baudin\otconda2\lib\site-packages\otfmi\otfmi.py", line 13, in <module>
    import pyfmi
  File "C:\Users\Baudin\otconda2\lib\site-packages\pyfmi\__init__.py", line 26, in <module>
    from .master import Master
  File "src\pyfmi\master.pyx", line 19, in init pyfmi.master (src\pyfmi\master.c:48285)
  File "C:\Users\Baudin\otconda2\lib\site-packages\pyfmi\fmi_algorithm_drivers.py", line 29, in <module>
    import pyfmi.fmi_extended as fmi_extended
  File "src\pyfmi\fmi_extended.pyx", line 26, in init pyfmi.fmi_extended (src\pyfmi\fmi_extended.c:11498)
  File "C:\Users\Baudin\otconda2\lib\site-packages\pyfmi\simulation\assimulo_interface.py", line 28, in <module>
    import pylab as P
  File "C:\Users\Baudin\otconda2\lib\site-packages\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\pylab.py", line 257, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\Users\Baudin\otconda2\lib\site-packages\matplotlib\backends\qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: La procÚdure spÚcifiÚe est introuvable.
```

* En Python, je n'arrive pas à charger le module otfmi :

```
from .otfmi import FMUFunction, OpenTURNSFMUFunction
Traceback (most recent call last):
  File "<ipython-input-4-8b9a8d6c3cb8>", line 1, in <module>
    from .otfmi import FMUFunction, OpenTURNSFMUFunction
ValueError: Attempted relative import in non-package
```

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 3, 2018, 14:16

mentioned in commit 6ad77f80f2a39627ead1f6447d68c731a1961e98

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 3, 2018, 14:17

mentioned in merge request !178

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Apr 3, 2018, 14:35

L'erreur Python est due à l'instruction 
```
from .otfmi import FMUFunction, OpenTURNSFMUFunction
```
qui n'est pas correcte en dehors d'un module, à cause du "." devant otfmi. Il faut faire plutôt :
```
from otfmi import FMUFunction, OpenTURNSFMUFunction
```
Dans ce cas, l'instruction marche correctement sur le poste.

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 3, 2018, 14:51

mentioned in commit f1e993f60e8da36d4d83b0b326219cd5e7f6543a

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 3, 2018, 15:50

!178

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 3, 2018, 15:50

closed

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Apr 26, 2018, 11:07

La version 4 finale ne permet pas d'importer les FMI qui fonctionnaient avec la version 3.

```
Traceback (most recent call last):
  File "C:\Users\c61372\AppData\Local\Continuum\otconda2\lib\site-packages\otfmi\fmi.py", line 33, in load_fmu
    return pyfmi.load_fmu(path_fmu, kind="auto")
  File "src\pyfmi\fmi.pyx", line 7201, in pyfmi.fmi.load_fmu (src\pyfmi\fmi.c:78974)
  File "src\pyfmi\fmi.pyx", line 5662, in pyfmi.fmi.FMUModelCS2.__init__ (src\pyfmi\fmi.c:63082)
  File "src\pyfmi\fmi.pyx", line 3420, in pyfmi.fmi.FMUModelBase2.__init__ (src\pyfmi\fmi.c:37621)
pyfmi.fmi.FMUException: Error loading the binary. The FMU contains no binary for
 this platform.
```

C'est un problème pour les utilisateurs intéressés par le FMI, qui ne peuvent pour l'instant utiliser que la version 3 de l'IHM.

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Apr 26, 2018, 11:07

reopened

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on Apr 26, 2018, 11:08

assigned to @schueller

**Comment by adumasphi** [comment]
In GitLab by @schueller on Apr 30, 2018, 10:57

Ce n'est pas le même problème.

**Comment by adumasphi** [comment]
In GitLab by @mbaudin on May 4, 2018, 10:37

OK : le ticket correct est le https://git.phimeca.com/ot-edf/otgui/issues/99
