### ISSUE TITLE
Le module otmorris n'est pas accessible dans la version Windows

### ISSUE THREAD

**Issue by adumasphi** [persalys/persalys#98]
In GitLab by @mbaudin on Apr 5, 2018, 14:06

Je souhaite tester la fonctionnalité de criblage sur la fonction de Morris. Pour cela, j'ai créé le modèle suivant.

[morris_model.py](/uploads/082e6ff48b2a0eb54e45f329f43dfd45/morris_model.py)

Cette fonction prend en argument 20 variables d'entrée et évalue la fonction myMorrisFunction. Cette fonction est définie dans l'étude suivante :

[morris_study.py](/uploads/dbf36e218ed338e5fd231fc42caed001/morris_study.py)

La fonction est créé sur la base du module otmorris, qui définit la classe MorrisFunction que le modèle utilise. 

L'étude utilise une boucle pour créer les 20 variables d'entrée du modèle. 

Ce script fonctionnait dans le contexte de SALOME sur un poste Linux, mais échoue sur Windows dans la version 4.0 fondée sur otconda. L'erreur est générée lors de l'import du module otmorris. La session suivante est exécutée depuis la console Python disponible dans l'IHM, en bas de la fenêtre principale :

```
>>> import otmorris
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Baudin\otconda2\lib\site-packages\otmorris\__init__.py", line 17, in <module>
    from .otmorris import *
  File "C:\Users\Baudin\otconda2\lib\site-packages\otmorris\otmorris.py", line 20, in <module>
    _otmorris = swig_import_helper()
  File "C:\Users\Baudin\otconda2\lib\site-packages\otmorris\otmorris.py", line 19, in swig_import_helper
    return importlib.import_module('_otmorris')
  File "C:\Users\Baudin\otconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _otmorris
```

Lorsqu'on exécute la même commande dans la console Python en dehors de l'interface graphique, l'instruction fonctionne correctement. Cela montre que le module otmorris est correctement installé sur le poste. Les deux exemples fournis dans le module otmorris fonctionnent également. J'ai réalisé ce test avec le module otconda sur un poste Windows.

**Comment by adumasphi** [comment]
In GitLab by @schueller on May 9, 2018, 19:26

closed via commit dae9190a03905579e67b453b5fa6881660ea566c

**Comment by adumasphi** [comment]
In GitLab by @schueller on May 9, 2018, 19:26

closed via merge request !182

**Comment by adumasphi** [comment]
In GitLab by @schueller on May 11, 2018, 10:03

mentioned in commit dae9190a03905579e67b453b5fa6881660ea566c
